### ISSUE TITLE
nproc: Command not found under macOS

### ISSUE THREAD

**Issue by leopku** [crazywolf132/ultimate-gomake#1]
macOS 11.7.10
go v1.23.3
GNU Make 3.81

**Comment by binbandit** [comment]
This should now be fixed. Some users on mac had it work, whilst others didn't. I for one did not have any issues, so thank you for raising this. Please let me know if I can close this now

**Comment by leopku** [comment]
This issue had fixed. Thanks.

But `make build` seems not work correctly. 

Need I close this issue and open a new issue for `make build`?

**Comment by binbandit** [comment]
> This issue had fixed. Thanks.
> 
> But `make build` seems not work correctly.
> 
> Need I close this issue and open a new issue for `make build`?

Yeah, lets open a seperate issue
